<a href="https://colab.research.google.com/github/ImenMasmoudiEm/CCKInternshipProject/blob/main/Ensembling_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import os 
os.chdir('/content/drive/MyDrive/All/Projects/Ing Internship/Data')

#Reading Data


In [ ]:
Tunnel=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/final-dataset.xlsx")
Tun=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/dataset1and2.xlsx")
Egiptien=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/dataset3and4.xlsx")
Libanon=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/D5.xlsx")

In [ ]:
#For the Tunnal Dataset
Tunnel['classe']=Tunnel['classe'].replace("hate", int(2))
Tunnel['classe']=Tunnel['classe'].replace("normal", int(0)) 
Tunnel['classe']=Tunnel['classe'].replace("abusive", int(1))


TunnelS = Tunnel['commentaire']
TunnelL = Tunnel['classe']

TunnalL = [int(i) for i in TunnelL]

In [ ]:
training_size=int(len(TunnelS)*0.8) 

training_sentences = TunnelS[0:training_size]
TunnelS = TunnelS[training_size:]
TunnelL = TunnelL[training_size:]

tokenizer = Tokenizer(num_words=3000, oov_token="<OOV>")
tokenizer.fit_on_texts(training_sentences)

vocab_size = len(tokenizer.word_index) + 1 

word_index = tokenizer.word_index

#For Tunnel Dataset
TunnelS = tokenizer.texts_to_sequences(TunnelS)
TunnelS207 = pad_sequences(TunnelS, maxlen=207, padding='post', truncating='post')
TunnelS388 = pad_sequences(TunnelS, maxlen=388, padding='post', truncating='post')

#For Tunisian Dataset
"""training_size=int(len(TunS)*0.8) 

TunS = TunS[training_size:]
TunL = TunL[training_size:]

TunS = tokenizer.texts_to_sequences(TunS)
TunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')
TunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')

#For Egiption Dataset
training_size=int(len(EgyS)*0.8) 

EgyS = EgyS[training_size:]
EgyL = EgyL[training_size:]

EgyS = tokenizer.texts_to_sequences(EgyS)
EgyS207 = pad_sequences(EgyS, maxlen=207, padding='post', truncating='post')
EgyS388 = pad_sequences(EgyS, maxlen=388, padding='post', truncating='post')

#For Libanon Dataset
training_size=int(len(TunS)*0.8) 

TunS = TunS[training_size:]
TunL = TunL[training_size:]

TunS = tokenizer.texts_to_sequences(TunS)
TunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')
TunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')"""

"training_size=int(len(TunS)*0.8) \n\nTunS = TunS[training_size:]\nTunL = TunL[training_size:]\n\nTunS = tokenizer.texts_to_sequences(TunS)\nTunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')\nTunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')\n\n#For Egiption Dataset\ntraining_size=int(len(EgyS)*0.8) \n\nEgyS = EgyS[training_size:]\nEgyL = EgyL[training_size:]\n\nEgyS = tokenizer.texts_to_sequences(EgyS)\nEgyS207 = pad_sequences(EgyS, maxlen=207, padding='post', truncating='post')\nEgyS388 = pad_sequences(EgyS, maxlen=388, padding='post', truncating='post')\n\n#For Libanon Dataset\ntraining_size=int(len(TunS)*0.8) \n\nTunS = TunS[training_size:]\nTunL = TunL[training_size:]\n\nTunS = tokenizer.texts_to_sequences(TunS)\nTunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')\nTunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')"

In [ ]:
#Importing the models
M1B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model1Balanced09.h5")
M1U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model1Unbalanced09.h5")
M2B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model2Balanced09.h5")
M2U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model2Unbalanced09.h5")
M3B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model3Balanced09.h5")
M3U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model3Unbalanced09.h5")

In [ ]:
def fcount(c,L):
  r=0
  for i in L:
    if i==c:
      r+=1
  return r

def MaxV(L1,L2,L3,L4,L5,L6):
  L=np.zeros(len(L1))
  for i in range(len(L1)):
    if (fcount(2,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(0,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])) and (fcount(2,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(1,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])):
      L[i]=2
    elif (fcount(1,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(0,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])):
      L[i]=1
    else:
      L[i]=0
  return L

In [ ]:
len(TunnelL)==len(TunnelP1)

True

In [ ]:
#Predictions for Tunnel
TunnelP1=M1B09.predict(TunnelS207)
TunnelP1=np.argmax(TunnelP1, axis=1).astype(int)

TunnelP2=M1U09.predict(TunnelS388)
TunnelP2=np.argmax(TunnelP2, axis=1).astype(int)

TunnelP3=M2B09.predict(TunnelS207)
TunnelP3=np.argmax(TunnelP3, axis=1).astype(int)

TunnelP4=M2U09.predict(TunnelS388)
TunnelP4=np.argmax(TunnelP4, axis=1).astype(int)

TunnelP5=M3B09.predict(TunnelS207)
TunnelP5=np.argmax(TunnelP5, axis=1).astype(int)

TunnelP6=M3U09.predict(TunnelS388)
TunnelP6=np.argmax(TunnelP6, axis=1).astype(int)

In [ ]:
TunnelP=MaxV(TunnelP1,TunnelP2,TunnelP3,TunnelP4,TunnelP5,TunnelP6)

cm = confusion_matrix(TunnelL, TunnelP)
print(cm)
print(classification_report(TunnelL, TunnelP, labels=[0,1,2]))

[[1818  365  512]
 [ 515  141  142]
 [ 731  198  185]]
              precision    recall  f1-score   support

           0       0.59      0.67      0.63      2695
           1       0.20      0.18      0.19       798
           2       0.22      0.17      0.19      1114

    accuracy                           0.47      4607
   macro avg       0.34      0.34      0.34      4607
weighted avg       0.44      0.47      0.45      4607



In [ ]:
for i in range(len(TunnelL)):
  print([TunnelP1[i],TunnelP2[i],TunnelP3[i],TunnelP4[i],TunnelP5[i],TunnelP6[i]]," the true value is: ", TunnelL[i], "P= ", TunnelP[i])

[0, 1, 0, 1, 0, 1]  the true value is:  0 P=  0.0
[1, 0, 1, 0, 1, 0]  the true value is:  2 P=  0.0
[2, 0, 2, 0, 2, 0]  the true value is:  0 P=  0.0
[2, 0, 2, 0, 2, 0]  the true value is:  0 P=  0.0
[2, 0, 2, 0, 2, 0]  the true value is:  0 P=  0.0
[2, 2, 2, 2, 2, 2]  the true value is:  0 P=  2.0
[1, 2, 1, 2, 1, 2]  the true value is:  0 P=  1.0
[2, 0, 2, 0, 2, 0]  the true value is:  0 P=  0.0
[0, 0, 0, 0, 0, 0]  the true value is:  0 P=  0.0
[0, 0, 0, 0, 0, 0]  the true value is:  0 P=  0.0
[0, 1, 0, 1, 0, 1]  the true value is:  0 P=  0.0
[0, 2, 0, 2, 0, 2]  the true value is:  0 P=  0.0
[0, 0, 0, 0, 0, 0]  the true value is:  0 P=  0.0
[1, 0, 1, 0, 1, 0]  the true value is:  2 P=  0.0
[2, 2, 2, 2, 2, 2]  the true value is:  0 P=  2.0
[2, 0, 2, 0, 2, 0]  the true value is:  2 P=  0.0
[2, 2, 0, 2, 0, 2]  the true value is:  2 P=  2.0
[1, 0, 1, 0, 1, 0]  the true value is:  0 P=  0.0
[1, 2, 1, 2, 1, 2]  the true value is:  1 P=  1.0
[2, 2, 2, 2, 2, 2]  the true value is:  0 P=  2.0


In [ ]:
X=np.zeros((4607,6))
for i in range(4607):
  X[i]=np.asarray([[TunnelP1[i],TunnelP2[i],TunnelP3[i],TunnelP4[i],TunnelP5[i],TunnelP6[i]]])

In [ ]:
TunnelL=np.asarray(TunnelL)

In [ ]:
model3 = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])
model3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 6)                 0         
                                                                 
 dense_2 (Dense)             (None, 128)               896       
                                                                 
 dense_3 (Dense)             (None, 24)                3096      
                                                                 
 dense_4 (Dense)             (None, 3)                 75        
                                                                 
Total params: 4,067
Trainable params: 4,067
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model3.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
history = model3.fit(X, TunnelL, epochs=50, verbose=1)

Epoch 1/50
144/144 [==============================] - 1s 2ms/step - loss: 0.9811 - accuracy: 0.5769
Epoch 2/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9619 - accuracy: 0.5850
Epoch 3/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9581 - accuracy: 0.5850
Epoch 4/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9592 - accuracy: 0.5850
Epoch 5/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9586 - accuracy: 0.5850
Epoch 6/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9574 - accuracy: 0.5850
Epoch 7/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9580 - accuracy: 0.5850
Epoch 8/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9580 - accuracy: 0.5850
Epoch 9/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9565 - accuracy: 0.5850
Epoch 10/50
144/144 [==============================] - 0s 2ms/step - loss: 0.9574 - accuracy: 0.5850