<a href="https://colab.research.google.com/github/ImenMasmoudiEm/CCKInternshipProject/blob/main/Ensembling_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import os 
os.chdir('/content/drive/MyDrive/All/Projects/Ing Internship/Data')

#Reading Data


In [3]:
Tunnel=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/final-dataset.xlsx")
Tun=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/dataset1and2.xlsx")
Lib=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/dataset3and4.xlsx")
Egy=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/D5.xlsx")

In [4]:
#For the Tunnal Dataset
Tunnel['classe']=Tunnel['classe'].replace("hate", int(2))
Tunnel['classe']=Tunnel['classe'].replace("normal", int(0)) 
Tunnel['classe']=Tunnel['classe'].replace("abusive", int(1))


TunnelS = Tunnel['commentaire']
TunnelL = Tunnel['classe']

TunnalL = [int(i) for i in TunnelL]

#For the Tunisian Dataset
Tun['classe']=Tun['classe'].replace("hate", int(2))
Tun['classe']=Tun['classe'].replace("normal", int(0)) 
Tun['classe']=Tun['classe'].replace("abusive", int(1))


TunS = Tun['commentaire']
TunL = Tun['classe']

TunL = [int(i) for i in TunL]

#For the Libanon Dataset
Lib['classe']=Lib['classe'].replace("hate", int(2))
Lib['classe']=Lib['classe'].replace("normal", int(0)) 
Lib['classe']=Lib['classe'].replace("abusive", int(1))


LibS = Lib['commentaire']
LibL = Lib['classe']

LibL = [int(i) for i in LibL]

#For the Egyptien Dataset
Egy['classe']=Egy['classe'].replace("hate", int(2))
Egy['classe']=Egy['classe'].replace("normal", int(0)) 
Egy['classe']=Egy['classe'].replace("abusive", int(1))


EgyS = Egy['commentaire']
EgyL = Egy['classe']

EgyL = [int(i) for i in EgyL]

In [5]:
training_size=int(len(TunnelS)*0.9) 

training_sentences = TunnelS[0:training_size]
TunnelS = TunnelS[training_size:]
TunnelL = TunnelL[training_size:]

tokenizer = Tokenizer(num_words=3000, oov_token="<OOV>")
tokenizer.fit_on_texts(training_sentences)

vocab_size = len(tokenizer.word_index) + 1 

word_index = tokenizer.word_index

#For Tunnel Dataset
TunnelS = tokenizer.texts_to_sequences(TunnelS)
TunnelS207 = pad_sequences(TunnelS, maxlen=207, padding='post', truncating='post')
TunnelS388 = pad_sequences(TunnelS, maxlen=388, padding='post', truncating='post')

#For Tunisian Dataset
training_size=int(len(TunS)*0.8) 

TunS = TunS[training_size:]
TunL = TunL[training_size:]

TunS = tokenizer.texts_to_sequences(TunS)
TunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')
TunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')

#For Libanon Dataset
training_size=int(len(LibS)*0.8) 

LibS = LibS[training_size:]
LibL = LibL[training_size:]

LibS = tokenizer.texts_to_sequences(LibS)
LibS207 = pad_sequences(LibS, maxlen=207, padding='post', truncating='post')
LibS388 = pad_sequences(LibS, maxlen=388, padding='post', truncating='post')

#For Egyptian Dataset
training_size=int(len(EgyS)*0.8)

EgyS = EgyS[training_size:]
EgyL = EgyL[training_size:]

EgyS = tokenizer.texts_to_sequences(EgyS)
EgyS207 = pad_sequences(EgyS, maxlen=207, padding='post', truncating='post')
EgyS388 = pad_sequences(EgyS, maxlen=388, padding='post', truncating='post')

In [6]:
#Importing the models
M1B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model1Balanced09.h5")
M1U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model1Unbalanced09.h5")
M2B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model2Balanced09.h5")
M2U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model2Unbalanced09.h5")
M3B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model3Balanced09.h5")
M3U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model3Unbalanced09.h5")

In [7]:
#Predictions for Tunnel
TunnelP11=M1B09.predict(TunnelS207)
TunnelP21=M1U09.predict(TunnelS388)
TunnelP31=M2B09.predict(TunnelS207)
TunnelP41=M2U09.predict(TunnelS388)
TunnelP51=M3B09.predict(TunnelS207)
TunnelP61=M3U09.predict(TunnelS388)

#Predictions for Tun
TunP11=M1B09.predict(TunS207)
TunP21=M1U09.predict(TunS388)
TunP31=M2B09.predict(TunS207)
TunP41=M2U09.predict(TunS388)
TunP51=M3B09.predict(TunS207)
TunP61=M3U09.predict(TunS388)

#Predictions for Lib
LibP11=M1B09.predict(LibS207)
LibP21=M1U09.predict(LibS388)
LibP31=M2B09.predict(LibS207)
LibP41=M2U09.predict(LibS388)
LibP51=M3B09.predict(LibS207)
LibP61=M3U09.predict(LibS388)

#Predictions for Egy
EgyP11=M1B09.predict(EgyS207)
EgyP21=M1U09.predict(EgyS388)
EgyP31=M2B09.predict(EgyS207)
EgyP41=M2U09.predict(EgyS388)
EgyP51=M3B09.predict(EgyS207)
EgyP61=M3U09.predict(EgyS388)

In [8]:
#First approach: Argmax and then look for the max

def fcount(c,L):
  r=0
  for i in L:
    if i==c:
      r+=1
  return r

def MaxV(L1,L2,L3,L4,L5,L6):
  L=np.zeros(len(L1))
  for i in range(len(L1)):
    if (fcount(2,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(0,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])) and (fcount(2,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(1,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])):
      L[i]=2
    elif (fcount(1,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(0,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])):
      L[i]=1
    else:
      L[i]=0
  return L

#For the Tunnel Dataset
TunnelP1=np.argmax(TunnelP11, axis=1).astype(int)
TunnelP2=np.argmax(TunnelP21, axis=1).astype(int)
TunnelP3=np.argmax(TunnelP31, axis=1).astype(int)
TunnelP4=np.argmax(TunnelP41, axis=1).astype(int)
TunnelP5=np.argmax(TunnelP51, axis=1).astype(int)
TunnelP6=np.argmax(TunnelP61, axis=1).astype(int)

TunnelP=MaxV(TunnelP1,TunnelP2,TunnelP3,TunnelP4,TunnelP5,TunnelP6)

cm = confusion_matrix(TunnelL, TunnelP)
print('Testing on the Tunnel Dataset')
print(cm)
print(classification_report(TunnelL, TunnelP, labels=[0,1,2]))

#For the Tunisian Dataset
TunP1=np.argmax(TunP11, axis=1).astype(int)
TunP2=np.argmax(TunP21, axis=1).astype(int)
TunP3=np.argmax(TunP31, axis=1).astype(int)
TunP4=np.argmax(TunP41, axis=1).astype(int)
TunP5=np.argmax(TunP51, axis=1).astype(int)
TunP6=np.argmax(TunP61, axis=1).astype(int)

TunP=MaxV(TunP1,TunP2,TunP3,TunP4,TunP5,TunP6)

cm = confusion_matrix(TunL, TunP)
print('Testing on the Tunisian Dataset')
print(cm)
print(classification_report(TunL, TunP, labels=[0,1,2]))

#For the Libanon Dataset
LibP1=np.argmax(LibP11, axis=1).astype(int)
LibP2=np.argmax(LibP21, axis=1).astype(int)
LibP3=np.argmax(LibP31, axis=1).astype(int)
LibP4=np.argmax(LibP41, axis=1).astype(int)
LibP5=np.argmax(LibP51, axis=1).astype(int)
LibP6=np.argmax(LibP61, axis=1).astype(int)

LibP=MaxV(LibP1,LibP2,LibP3,LibP4,LibP5,LibP6)

cm = confusion_matrix(LibL, LibP)
print('Testing on the Libanon Dataset')
print(cm)
print(classification_report(LibL, LibP, labels=[0,1,2]))

#For the Egyptian Dataset
EgyP1=np.argmax(EgyP11, axis=1).astype(int)
EgyP2=np.argmax(EgyP21, axis=1).astype(int)
EgyP3=np.argmax(EgyP31, axis=1).astype(int)
EgyP4=np.argmax(EgyP41, axis=1).astype(int)
EgyP5=np.argmax(EgyP51, axis=1).astype(int)
EgyP6=np.argmax(EgyP61, axis=1).astype(int)

EgyP=MaxV(EgyP1,EgyP2,EgyP3,EgyP4,EgyP5,EgyP6)

cm = confusion_matrix(EgyL, EgyP)
print('Testing on the Egyptian Dataset')
print(cm)
print(classification_report(EgyL, EgyP, labels=[0,1,2]))

Testing on the Tunnel Dataset
[[1256    3    6]
 [ 135  268   11]
 [ 187  100  338]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.88      1265
           1       0.72      0.65      0.68       414
           2       0.95      0.54      0.69       625

    accuracy                           0.81      2304
   macro avg       0.82      0.73      0.75      2304
weighted avg       0.83      0.81      0.79      2304

Testing on the Tunisian Dataset
[[516  44  27]
 [118 126   9]
 [176 131 145]]
              precision    recall  f1-score   support

           0       0.64      0.88      0.74       587
           1       0.42      0.50      0.45       253
           2       0.80      0.32      0.46       452

    accuracy                           0.61      1292
   macro avg       0.62      0.57      0.55      1292
weighted avg       0.65      0.61      0.58      1292

Testing on the Libanon Dataset
[[511   3  12]
 [  1   5   1]
 [356 182 769]

In [9]:
#Second approach: We add the predictions and then we apply Argmax

#Testing on the Tunnel Dataset
TunnelPF=np.asarray(TunnelP11)+np.asarray(TunnelP21)+np.asarray(TunnelP31)+np.asarray(TunnelP41)+np.asarray(TunnelP51)+np.asarray(TunnelP61)
TunnelPF=np.argmax(TunnelPF, axis=1).astype(int)

cm = confusion_matrix(TunnelL, TunnelPF)
print('Testing on the Tunnel Dataset')
print(cm)
print(classification_report(TunnelL, TunnelPF, labels=[0,1,2]))

#Testing on the Tunisian Dataset
TunPF=np.asarray(TunP11)+np.asarray(TunP21)+np.asarray(TunP31)+np.asarray(TunP41)+np.asarray(TunP51)+np.asarray(TunP61)
TunPF=np.argmax(TunPF, axis=1).astype(int)

cm = confusion_matrix(TunL, TunPF)
print('Testing on the Tunisian Dataset')
print(cm)
print(classification_report(TunL, TunPF, labels=[0,1,2]))

#Testing on the Libanon Dataset
LibPF=np.asarray(LibP11)+np.asarray(LibP21)+np.asarray(LibP31)+np.asarray(LibP41)+np.asarray(LibP51)+np.asarray(LibP61)
LibPF=np.argmax(LibPF, axis=1).astype(int)

cm = confusion_matrix(LibL, LibPF)
print('Testing on the Libanon Dataset')
print(cm)
print(classification_report(LibL, LibPF, labels=[0,1,2]))

#Testing on the Egyptian Dataset
EgyPF=np.asarray(EgyP11)+np.asarray(EgyP21)+np.asarray(EgyP31)+np.asarray(EgyP41)+np.asarray(EgyP51)+np.asarray(EgyP61)
EgyPF=np.argmax(EgyPF, axis=1).astype(int)

cm = confusion_matrix(EgyL, EgyPF)
print('Testing on the Egyptian Dataset')
print(cm)
print(classification_report(EgyL, EgyPF, labels=[0,1,2]))

Testing on the Tunnel Dataset
[[1157   41   67]
 [  63  292   59]
 [  90   50  485]]
              precision    recall  f1-score   support

           0       0.88      0.91      0.90      1265
           1       0.76      0.71      0.73       414
           2       0.79      0.78      0.78       625

    accuracy                           0.84      2304
   macro avg       0.81      0.80      0.81      2304
weighted avg       0.84      0.84      0.84      2304

Testing on the Tunisian Dataset
[[464  64  59]
 [ 53 175  25]
 [ 96 144 212]]
              precision    recall  f1-score   support

           0       0.76      0.79      0.77       587
           1       0.46      0.69      0.55       253
           2       0.72      0.47      0.57       452

    accuracy                           0.66      1292
   macro avg       0.64      0.65      0.63      1292
weighted avg       0.68      0.66      0.66      1292

Testing on the Libanon Dataset
[[ 415   37   74]
 [   0    3    4]
 [ 136  

In [10]:
#Third approach: We use a Neural Network Model

#The Tunnel Dataset
TunnelL=np.asarray(TunnelL)
TunnelP=np.asarray(TunnelP)
XTunnel=[]
for i in range(len(TunnelL)):
  #print([TunnelP1[i],TunnelP2[i],TunnelP3[i],TunnelP4[i],TunnelP5[i],TunnelP6[i]]," the true value is: ", TunnelL[i], "P= ", TunnelP[i])
  XTunnel.append([TunnelP1[i],TunnelP2[i],TunnelP3[i],TunnelP4[i],TunnelP5[i],TunnelP6[i]])

#The Tunisian Dataset
TunL=np.asarray(TunL)
TunP=np.asarray(TunP)
XTun=[]
for i in range(len(TunL)):
  XTun.append([TunP1[i],TunP2[i],TunP3[i],TunP4[i],TunP5[i],TunP6[i]])

#The Libanon Dataset
LibL=np.asarray(LibL)
LibP=np.asarray(LibP)
XLib=[]
for i in range(len(LibL)):
  XLib.append([LibP1[i],LibP2[i],LibP3[i],LibP4[i],LibP5[i],LibP6[i]])

#The Egyptian Dataset
EgyL=np.asarray(EgyL)
EgyP=np.asarray(EgyP)
XEgy=[]
for i in range(len(EgyL)):
  XEgy.append([EgyP1[i],EgyP2[i],EgyP3[i],EgyP4[i],EgyP5[i],EgyP6[i]])

In [11]:
TunnelL=np.asarray(TunnelL)
TunL=np.asarray(TunL)
EgyL=np.asarray(EgyL)
LibL=np.asarray(LibL)

XTunnel=np.asarray(XTunnel)
XTun=np.asarray(XTun)
XEgy=np.asarray(XEgy)
XLib=np.asarray(XLib)

In [12]:
FEModelTunnel = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='sigmoid'),
    tf.keras.layers.Dense(24, activation='selu'),
    tf.keras.layers.Dense(3, activation='softmax')
])
FEModelTunnel.summary()
FEModelTun = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='sigmoid'),
    tf.keras.layers.Dense(24, activation='selu'),
    tf.keras.layers.Dense(3, activation='softmax')
])
FEModelLib = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='sigmoid'),
    tf.keras.layers.Dense(24, activation='selu'),
    tf.keras.layers.Dense(3, activation='softmax')
])
FEModelEgy = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='sigmoid'),
    tf.keras.layers.Dense(24, activation='selu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 6)                 0         
                                                                 
 dense (Dense)               (None, 128)               896       
                                                                 
 dense_1 (Dense)             (None, 24)                3096      
                                                                 
 dense_2 (Dense)             (None, 3)                 75        
                                                                 
Total params: 4,067
Trainable params: 4,067
Non-trainable params: 0
_________________________________________________________________


In [14]:
FEModelTunnel.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
history = FEModelTunnel.fit(XTunnel, TunnelL, epochs=50, verbose=1)

FEModelTun.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
history = FEModelTun.fit(XTun, TunL, epochs=50, verbose=1)

FEModelLib.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
history = FEModelLib.fit(XLib, LibL, epochs=50, verbose=1)

FEModelEgy.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
history = FEModelEgy.fit(XEgy, EgyL, epochs=50, verbose=1)

Epoch 1/50
72/72 [==============================] - 1s 2ms/step - loss: 0.7016 - accuracy: 0.7292
Epoch 2/50
72/72 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8898
Epoch 3/50
72/72 [==============================] - 0s 2ms/step - loss: 0.3240 - accuracy: 0.9588
Epoch 4/50
72/72 [==============================] - 0s 2ms/step - loss: 0.3011 - accuracy: 0.9588
Epoch 5/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2968 - accuracy: 0.9588
Epoch 6/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2920 - accuracy: 0.9588
Epoch 7/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2917 - accuracy: 0.9588
Epoch 8/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2823 - accuracy: 0.9588
Epoch 9/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2782 - accuracy: 0.9588
Epoch 10/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2703 - accuracy: 0.9588
Epoch 11/50
72/72 [

In [15]:
TunnelFP=FEModelTunnel.predict(XTunnel)
TunFP=FEModelTun.predict(XTun)
EgyFP=FEModelEgy.predict(XEgy)
LibFP=FEModelLib.predict(XLib)

In [18]:
#Testing Third approach on the Tunnel Dataset
TunnelFP=np.argmax(TunnelFP, axis=1).astype(int)
cm = confusion_matrix(TunnelL, TunnelFP)
print('Testing on the Tunnel Dataset')
print(cm)
print(classification_report(TunnelL, TunnelFP, labels=[0,1,2]))

#Testing Third approach on the Tunisian Dataset
TunFP=np.argmax(TunFP, axis=1).astype(int)
cm = confusion_matrix(TunL, TunFP)
print('Testing on the Tunisian Dataset')
print(cm)
print(classification_report(TunL, TunFP, labels=[0,1,2]))

#Testing Third approach on the Libanon Dataset
LibFP=np.argmax(LibFP, axis=1).astype(int)
cm = confusion_matrix(LibL, LibFP)
print('Testing on the Libanon Dataset')
print(cm)
print(classification_report(LibL, LibFP, labels=[0,1,2]))

#Testing Third approach on the Egyptian Dataset
EgyFP=np.argmax(EgyFP, axis=1).astype(int)
cm = confusion_matrix(EgyL, EgyFP)
print('Testing on the Egyptian Dataset')
print(cm)
print(classification_report(EgyL, EgyFP, labels=[0,1,2]))

Testing on the Tunnel Dataset
[[1254    2    9]
 [  15  375   24]
 [  33   12  580]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1265
           1       0.96      0.91      0.93       414
           2       0.95      0.93      0.94       625

    accuracy                           0.96      2304
   macro avg       0.96      0.94      0.95      2304
weighted avg       0.96      0.96      0.96      2304

Testing on the Tunisian Dataset
[[492   2  93]
 [ 49  16 188]
 [ 73   8 371]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82       587
           1       0.62      0.06      0.11       253
           2       0.57      0.82      0.67       452

    accuracy                           0.68      1292
   macro avg       0.66      0.57      0.54      1292
weighted avg       0.68      0.68      0.63      1292

Testing on the Libanon Dataset
[[ 502    0   24]
 [   2    0    5]
 [   8  

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
