<a href="https://colab.research.google.com/github/ImenMasmoudiEm/CCKInternshipProject/blob/main/Ensembling_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import os 
os.chdir('/content/drive/MyDrive/All/Projects/Ing Internship/Data')

#Reading Data


In [13]:
Tunnel=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/final-dataset.xlsx")
Tun=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/dataset1and2.xlsx")
Egiptien=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/dataset3and4.xlsx")
Libanon=pd.read_excel("/content/drive/MyDrive/All/Projects/Ing Internship/Data/D5.xlsx")

In [14]:
#For the Tunnal Dataset
Tunnel['classe']=Tunnel['classe'].replace("hate", int(2))
Tunnel['classe']=Tunnel['classe'].replace("normal", int(0)) 
Tunnel['classe']=Tunnel['classe'].replace("abusive", int(1))


TunnelS = Tunnel['commentaire']
TunnelL = Tunnel['classe']

TunnalL = [int(i) for i in TunnelL]

In [15]:
training_size=int(len(TunnelS)*0.9) 

training_sentences = TunnelS[0:training_size]
TunnelS = TunnelS[training_size:]
TunnelL = TunnelL[training_size:]

tokenizer = Tokenizer(num_words=3000, oov_token="<OOV>")
tokenizer.fit_on_texts(training_sentences)

vocab_size = len(tokenizer.word_index) + 1 

word_index = tokenizer.word_index

#For Tunnel Dataset
TunnelS = tokenizer.texts_to_sequences(TunnelS)
TunnelS207 = pad_sequences(TunnelS, maxlen=207, padding='post', truncating='post')
TunnelS388 = pad_sequences(TunnelS, maxlen=388, padding='post', truncating='post')

#For Tunisian Dataset
"""training_size=int(len(TunS)*0.8) 

TunS = TunS[training_size:]
TunL = TunL[training_size:]

TunS = tokenizer.texts_to_sequences(TunS)
TunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')
TunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')

#For Egiption Dataset
training_size=int(len(EgyS)*0.8) 

EgyS = EgyS[training_size:]
EgyL = EgyL[training_size:]

EgyS = tokenizer.texts_to_sequences(EgyS)
EgyS207 = pad_sequences(EgyS, maxlen=207, padding='post', truncating='post')
EgyS388 = pad_sequences(EgyS, maxlen=388, padding='post', truncating='post')

#For Libanon Dataset
training_size=int(len(TunS)*0.8) 

TunS = TunS[training_size:]
TunL = TunL[training_size:]

TunS = tokenizer.texts_to_sequences(TunS)
TunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')
TunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')"""

"training_size=int(len(TunS)*0.8) \n\nTunS = TunS[training_size:]\nTunL = TunL[training_size:]\n\nTunS = tokenizer.texts_to_sequences(TunS)\nTunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')\nTunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')\n\n#For Egiption Dataset\ntraining_size=int(len(EgyS)*0.8) \n\nEgyS = EgyS[training_size:]\nEgyL = EgyL[training_size:]\n\nEgyS = tokenizer.texts_to_sequences(EgyS)\nEgyS207 = pad_sequences(EgyS, maxlen=207, padding='post', truncating='post')\nEgyS388 = pad_sequences(EgyS, maxlen=388, padding='post', truncating='post')\n\n#For Libanon Dataset\ntraining_size=int(len(TunS)*0.8) \n\nTunS = TunS[training_size:]\nTunL = TunL[training_size:]\n\nTunS = tokenizer.texts_to_sequences(TunS)\nTunS207 = pad_sequences(TunS, maxlen=207, padding='post', truncating='post')\nTunS388 = pad_sequences(TunS, maxlen=388, padding='post', truncating='post')"

In [6]:
#Importing the models
M1B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model1Balanced09.h5")
M1U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model1Unbalanced09.h5")
M2B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model2Balanced09.h5")
M2U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model2Unbalanced09.h5")
M3B09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Balanced 09/Model3Balanced09.h5")
M3U09=tf.keras.models.load_model("/content/drive/MyDrive/All/Projects/Ing Internship/Data/Unbalanced 09/Model3Unbalanced09.h5")

In [16]:
def fcount(c,L):
  r=0
  for i in L:
    if i==c:
      r+=1
  return r

def MaxV(L1,L2,L3,L4,L5,L6):
  L=np.zeros(len(L1))
  for i in range(len(L1)):
    if (fcount(2,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(0,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])) and (fcount(2,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(1,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])):
      L[i]=2
    elif (fcount(1,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])>fcount(0,[L1[i],L2[i],L3[i],L4[i],L5[i],L6[i]])):
      L[i]=1
    else:
      L[i]=0
  return L

In [17]:
#Predictions for Tunnel
TunnelP1=M1B09.predict(TunnelS207)
TunnelP1=np.argmax(TunnelP1, axis=1).astype(int)

TunnelP2=M1U09.predict(TunnelS388)
TunnelP2=np.argmax(TunnelP2, axis=1).astype(int)

TunnelP3=M2B09.predict(TunnelS207)
TunnelP3=np.argmax(TunnelP3, axis=1).astype(int)

TunnelP4=M2U09.predict(TunnelS388)
TunnelP4=np.argmax(TunnelP4, axis=1).astype(int)

TunnelP5=M3B09.predict(TunnelS207)
TunnelP5=np.argmax(TunnelP5, axis=1).astype(int)

TunnelP6=M3U09.predict(TunnelS388)
TunnelP6=np.argmax(TunnelP6, axis=1).astype(int)

In [19]:
TunnelP=MaxV(TunnelP1,TunnelP2,TunnelP3,TunnelP4,TunnelP5,TunnelP6)

cm = confusion_matrix(TunnelL, TunnelP)
print(cm)
print(classification_report(TunnelL, TunnelP, labels=[0,1,2]))

[[1256    3    6]
 [ 135  268   11]
 [ 187  100  338]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.88      1265
           1       0.72      0.65      0.68       414
           2       0.95      0.54      0.69       625

    accuracy                           0.81      2304
   macro avg       0.82      0.73      0.75      2304
weighted avg       0.83      0.81      0.79      2304



In [54]:
TunnelL=np.asarray(TunnelL)
TunnelP=np.asarray(TunnelP)
X=[]
for i in range(len(TunnelL)):
  #print([TunnelP1[i],TunnelP2[i],TunnelP3[i],TunnelP4[i],TunnelP5[i],TunnelP6[i]]," the true value is: ", TunnelL[i], "P= ", TunnelP[i])
  X.append([TunnelP1[i],TunnelP2[i],TunnelP3[i],TunnelP4[i],TunnelP5[i],TunnelP6[i]])

In [40]:
X=np.asarray(X)

In [ ]:
TunnelL=np.asarray(TunnelL)

In [50]:
FEModel = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='sigmoid'),
    tf.keras.layers.Dense(24, activation='selu'),
    tf.keras.layers.Dense(3, activation='softmax')
])
FEModel.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 6)                 0         
                                                                 
 dense_8 (Dense)             (None, 128)               896       
                                                                 
 dense_9 (Dense)             (None, 24)                3096      
                                                                 
 dense_10 (Dense)            (None, 3)                 75        
                                                                 
Total params: 4,067
Trainable params: 4,067
Non-trainable params: 0
_________________________________________________________________


In [51]:
FEModel.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
history = FEModel.fit(X, TunnelL, epochs=50, verbose=1)

Epoch 1/50
72/72 [==============================] - 0s 2ms/step - loss: 0.7418 - accuracy: 0.7079
Epoch 2/50
72/72 [==============================] - 0s 2ms/step - loss: 0.4334 - accuracy: 0.8832
Epoch 3/50
72/72 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.9575
Epoch 4/50
72/72 [==============================] - 0s 2ms/step - loss: 0.3140 - accuracy: 0.9562
Epoch 5/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2985 - accuracy: 0.9588
Epoch 6/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2931 - accuracy: 0.9588
Epoch 7/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2841 - accuracy: 0.9588
Epoch 8/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2775 - accuracy: 0.9588
Epoch 9/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2732 - accuracy: 0.9588
Epoch 10/50
72/72 [==============================] - 0s 2ms/step - loss: 0.2610 - accuracy: 0.9588
Epoch 11/50
72/72 [

In [52]:
TunnelFP=FEModel.predict(X)

In [53]:
TunnelFP=np.argmax(TunnelFP, axis=1).astype(int)
cm = confusion_matrix(TunnelL, TunnelFP)
print(cm)
print(classification_report(TunnelL, TunnelFP, labels=[0,1,2]))

[[1254    2    9]
 [  15  375   24]
 [  33   12  580]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1265
           1       0.96      0.91      0.93       414
           2       0.95      0.93      0.94       625

    accuracy                           0.96      2304
   macro avg       0.96      0.94      0.95      2304
weighted avg       0.96      0.96      0.96      2304

